version = 3
final_space = true

[secondary_prompt]
  template = '❯❯ '
  foreground = 'magenta'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  foreground = ''
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}green{{end}}', '{{if eq .Code 0}}magenta{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ''
    template = '{{ if .SSHSession }}󰣀 {{ .UserName }}@{{ .HostName }} {{else}}󰌢 {{end}}'
    foreground = '#f8f8f2'
    background = '#6272a4'
    type = 'session'

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ .Path }} '
    foreground = '#f8f8f2'
    powerline_symbol = ''
    background = '#bd93f9'
    type = 'path'

    [blocks.segments.properties]
      style = 'folder'

      [blocks.segments.properties.mapped_locations]
        '/mnt/c' = ''
        'C:/' = ''
        '~/.config' = ''
        '~/Desktop' = '󰍹'
        '~/Developer' = ''
        '~/Documents' = '󰧮'
        '~/Downloads' = '󰇚'
        '~/Music' = '󰎇'
        '~/Pictures' = '󰥶'
        '~/Repos' = ''
        '~/Sounds' = ''
        '~/Videos' = ''
        '~/iCloudDrive' = '󰀸'

  [[blocks.segments]]
    style = 'powerline'
    template = '  {{ .HEAD }}{{ if gt .StashCount 0 }} ( {{ .StashCount }}){{ end }} '
    foreground = '#f8f8f2'
    powerline_symbol = ''
    background = '#ffb86c'
    type = 'git'

    [blocks.segments.properties]
      branch_icon = ''
      fetch_stash_count = true
      fetch_status = false
      fetch_upstream_icon = true

  [[blocks.segments]]
    style = 'powerline'
    template = '  {{if .Venv}}{{.Venv}} ({{.Full}}) {{end}}'
    foreground = '#F8F8F2'
    powerline_symbol = ''
    background = '#8BE9FD'
    type = 'python'

    [blocks.segments.properties]
      fetch_virtualenv = true
      home_enabled = true

  [[blocks.segments]]
    style = 'powerline'
    template = '  {{ .Full }} '
    foreground = '#F8F8F2'
    powerline_symbol = ''
    background = '#8BE9FD'
    type = 'node'

    [blocks.segments.properties]
      fetch_package_manager = true

  [[blocks.segments]]
    style = 'plain'
    template = ""
    foreground = '#f8f8f2'
    background = '#ff5555'
    type = 'text'

[[blocks]]
  type = 'rprompt'
  alignment = 'right'
  overflow = 'hidden'

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    template = '  {{.Profile}}{{if .Region}}@{{.Region}}{{end}}'
    foreground = '#282a36'
    background = '#f1fa8c'
    type = 'aws'
    invert_powerline = true

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ''
    template = '  {{ .FormattedMs }} '
    foreground = '#282a36'
    background = '#f1fa8c'
    type = 'executiontime'
    invert_powerline = true

    [blocks.segments.properties]
      threshold = 5000

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    template = ' ♥ {{ .CurrentDate | date .Format }}'
    foreground = '#f8f8f2'
    background = '#ff79c6'
    type = 'time'
    invert_powerline = true

    [blocks.segments.properties]
      time_format = '15:04'
